### ISSUE TITLE
bug: Very long LdPagination size increases parents container width 

### ISSUE THREAD

**Issue by mkilp** [emdgroup-liquid/liquid#1049]
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://liquid.merck.design/liquid/guides/contributing/#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

latest

### Framework bindings

React

### Current behavior

A very long LdPagination in a container with max-width causes scrolling to overflow.

### Expected behavior

Scrolling should not overflow.

### Steps to reproduce

See Code repo.

### Code reproduction URL

https://codesandbox.io/p/devbox/ldpagination-28fjz2?file=%2Fsrc%2FApp.js%3A16%2C1

**Comment by renet** [comment]
It seems like the `text-align: center;` style on the `.App` class in the css file is causing these issues. To center-align the pagination, please consider removing this style and adding `margin: auto;` to the `Container`, instead. This should fix the issue.

@mkilp Can you confirm that this fixes the issue?

**Comment by mkilp** [comment]
@renet Your suggestions did not fix the issue unfortunately. 
In our prod application we had to play around with overflow-x: hidden; on some of the parent containers but that is obviously not intended.

I updated the codesandbox with your suggestions for your to review.

**Comment by renet** [comment]
@mkilp The `margin: auto;` should not be added to the `.App`, but to the `Container` (using styled components). Does this help?

If this does not help in your production environment, please add a sandbox showcasing exactly the issue that you're having in the prod environment.

**Comment by mkilp** [comment]
@renet adding `margin:auto;` does to the container does sadly not do anything. 

Even in the sandbox the component is still causing the container / page to overflow. I removed the container and any added styles. I'd assume the hidden numbers should not cause the page to go that wide but fit within the existing viewport.
![image](https://github.com/emdgroup-liquid/liquid/assets/8791079/8f5d0fc7-c2ed-474e-9cf0-a4a579267098)

**Comment by renet** [comment]
Ah, I totally get your point now. I was mislead by the more obvious visual bug that was cause by `text-align: center;` in the sandbox. I got you now and will look into this. There is a workaround that should fix this issue:

```css
ld-pagination::part(wrapper) {
  overflow: hidden;
}
```
should do the job. Can you please confirm?

**Comment by renet** [comment]
@mkilp Did the last workaround solve your problem?
